OPENAI_API_KEY="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"
OPENAI_ASSISTANT_ID="asst_VJZ2bkhVvyXUgzPkkvJ2Y5us"